import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#10B981',
  primaryDark: '#059669',
  primaryLight: '#ECFDF5',
  dark: '#111827',
  text: '#111827',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E5E7EB',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  error: '#EF4444',
  errorLight: '#FEF2F2',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: COLORS.background,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 40,
    color: COLORS.text,
    lineHeight: 34,
  },
  subtitle: {
    textAlign: 'center',
    marginBottom: 30,
    fontWeight: '500',
    color: COLORS.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  input: {
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    fontSize: 15,
    color: COLORS.text,
    backgroundColor: COLORS.surface,
  },
  primaryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 10,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    marginBottom: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
  },
  secondaryButton: {
    backgroundColor: COLORS.surface,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    marginBottom: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    textAlign: 'center',
    fontWeight: '600',
    color: COLORS.text,
    fontSize: 16,
  },
  or: {
    textAlign: 'center',
    marginVertical: 12,
    color: COLORS.textMuted,
  },
  resend: {
    textAlign: 'center',
    color: COLORS.textMuted,
    marginBottom: 20,
  },
  logo: {
    marginTop: 60,
    width: 90,
    height: 90,
    marginBottom: 20,
    alignSelf: 'center',
    borderRadius: 18,
  },
});

