import { router, useLocalSearchParams, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import React, { useState, useCallback } from 'react';
import {
  Alert,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { CameraView, useCameraPermissions, BarcodeScanningResult } from 'expo-camera';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { globalStyles } from '../../src/styles/globalStyles';

/**
 * PumpAuthScreen — QR Code Verification
 *
 * The kiosk hardware displays a one-time QR code on its screen after the
 * user reserves a pump. The user scans that QR with their phone camera to
 * prove physical presence and activate the pump.
 *
 * QR payload format (JSON, generated by the kiosk):
 *   { "stationId": "...", "nozzle": "1", "token": "RAND-XXXX", "ts": 1234567890 }
 *
 * The token is refreshed by the kiosk after every completed transaction so it
 * can never be replayed. In production, the backend verifies the token.
 * In demo mode, any QR with a matching stationId is accepted.
 */

export default function PumpAuthScreen() {
  const insets = useSafeAreaInsets();
  const params = useLocalSearchParams();

  const stationId    = params.stationId as string;
  const product      = params.product as string;
  const presetType   = params.presetType as string;
  const presetValue  = params.presetValue as string;
  const holdAmount   = params.holdAmount as string;
  const holdAmountRaw = params.holdAmountRaw as string;
  const nozzle       = params.nozzle as string;
  const stationName  = params.stationName as string;

  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false);
  const [active, setActive] = useState(true);

  // Pause scanner when navigating away; reset on return
  useFocusEffect(
    useCallback(() => {
      setScanned(false);
      setActive(true);
      return () => setActive(false);
    }, [])
  );

  const handleBarcodeScan = ({ data }: BarcodeScanningResult) => {
    if (scanned || !active) return;
    setScanned(true);
    setActive(false);

    let payload: Record<string, string> = {};

    // Parse JSON payload; fall back to treating raw text as a passthrough
    try {
      const parsed = JSON.parse(data);
      payload = {
        stationId: String(parsed.stationId ?? ''),
        nozzle:    String(parsed.nozzle ?? ''),
        token:     String(parsed.token ?? ''),
      };
    } catch {
      // Raw text from kiosk — treat as a passthrough token (no stationId check)
      payload = { stationId, nozzle, token: data };
    }

    // Reject QR codes from a different station
    if (payload.stationId && payload.stationId !== stationId) {
      Alert.alert(
        'Wrong Station',
        'This QR code belongs to a different station. Please scan the QR code on your reserved pump.',
        [{ text: 'Try Again', onPress: () => { setScanned(false); setActive(true); } }]
      );
      return;
    }

    // Reject QR codes for a different nozzle (optional field)
    if (payload.nozzle && payload.nozzle !== nozzle) {
      Alert.alert(
        'Wrong Pump',
        `This QR belongs to pump #${payload.nozzle}, but you reserved pump #${nozzle}. Please scan the correct pump.`,
        [{ text: 'Try Again', onPress: () => { setScanned(false); setActive(true); } }]
      );
      return;
    }

    // All checks passed — activate the pump
    router.push({
      pathname: './live-dispensing',
      params: { stationId, product, presetType, presetValue, holdAmount, holdAmountRaw, nozzle },
    });
  };

  // ── Permission states ──────────────────────────────────────────────────────

  if (!permission) {
    return (
      <View style={[styles.screen, { justifyContent: 'center', alignItems: 'center' }]}>
        <Text style={styles.permText}>Requesting camera access…</Text>
      </View>
    );
  }

  if (!permission.granted) {
    return (
      <View style={[styles.screen, { paddingTop: insets.top }]}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={22} color="#111827" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Pump Verification</Text>
          <View style={{ width: 38 }} />
        </View>
        <View style={styles.permContainer}>
          <View style={styles.permIconBox}>
            <Ionicons name="camera-outline" size={48} color="#10B981" />
          </View>
          <Text style={styles.permTitle}>Camera Access Required</Text>
          <Text style={styles.permSubtitle}>
            To verify your pump reservation, allow camera access so you can scan
            the QR code displayed on the kiosk screen.
          </Text>
          <TouchableOpacity style={[globalStyles.primaryButton, { marginTop: 24 }]} onPress={requestPermission}>
            <Text style={globalStyles.primaryButtonText}>Allow Camera</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[globalStyles.secondaryButton, { marginTop: 12 }]} onPress={() => router.back()}>
            <Text style={globalStyles.secondaryButtonText}>Go Back</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  // ── Main scanner UI ────────────────────────────────────────────────────────

  return (
    <View style={[styles.screen, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={22} color="#111827" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Pump Verification</Text>
        <View style={{ width: 38 }} />
      </View>

      {/* Station info strip */}
      <View style={styles.stationStrip}>
        <Ionicons name="location-outline" size={16} color="#10B981" />
        <Text style={styles.stationStripName} numberOfLines={1}>{stationName || 'Station'}</Text>
        <View style={styles.pumpBadge}>
          <Ionicons name="checkmark-circle" size={13} color="#10B981" />
          <Text style={styles.pumpBadgeText}>Pump #{nozzle} Reserved</Text>
        </View>
      </View>

      {/* Camera viewport */}
      <View style={styles.cameraContainer}>
        <CameraView
          style={StyleSheet.absoluteFillObject}
          facing="back"
          active={active && !scanned}
          onBarcodeScanned={scanned ? undefined : handleBarcodeScan}
          barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
        />

        {/* Dark overlay with transparent scan window */}
        <View style={styles.overlay}>
          <View style={styles.overlayRow} />
          <View style={styles.overlayMiddle}>
            <View style={styles.overlaySide} />
            <View style={styles.scanWindow}>
              <View style={[styles.corner, styles.cornerTL]} />
              <View style={[styles.corner, styles.cornerTR]} />
              <View style={[styles.corner, styles.cornerBL]} />
              <View style={[styles.corner, styles.cornerBR]} />
            </View>
            <View style={styles.overlaySide} />
          </View>
          <View style={styles.overlayRow} />
        </View>
      </View>

      {/* Instructions */}
      <View style={styles.instructions}>
        <Ionicons name="qr-code-outline" size={22} color="#10B981" style={{ marginBottom: 8 }} />
        <Text style={styles.instructTitle}>Scan the kiosk QR code</Text>
        <Text style={styles.instructSub}>
          Point your camera at the QR code on pump #{nozzle} screen.{'\n'}
          The QR refreshes automatically after every transaction.
        </Text>

        {scanned && (
          <TouchableOpacity
            style={[globalStyles.secondaryButton, { marginTop: 16 }]}
            onPress={() => { setScanned(false); setActive(true); }}
          >
            <Text style={globalStyles.secondaryButtonText}>Scan Again</Text>
          </TouchableOpacity>
        )}

        <TouchableOpacity style={styles.backLink} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={14} color="#9CA3AF" />
          <Text style={styles.backLinkText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const WINDOW = 240;
const CORNER = 22;
const CORNER_W = 4;

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F8FAFC' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    backgroundColor: '#fff',
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: { fontSize: 17, fontWeight: '700', color: '#111827' },

  stationStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#ECFDF5',
    borderBottomWidth: 1,
    borderBottomColor: '#A7F3D0',
  },
  stationStripName: { flex: 1, fontSize: 13, fontWeight: '600', color: '#065F46' },
  pumpBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  pumpBadgeText: { fontSize: 12, fontWeight: '600', color: '#059669' },

  cameraContainer: { flex: 1, overflow: 'hidden' },

  overlay: { ...StyleSheet.absoluteFillObject, flexDirection: 'column' },
  overlayRow: { flex: 1, backgroundColor: 'rgba(0,0,0,0.52)' },
  overlayMiddle: { flexDirection: 'row', height: WINDOW },
  overlaySide: { flex: 1, backgroundColor: 'rgba(0,0,0,0.52)' },
  scanWindow: { width: WINDOW, height: WINDOW, backgroundColor: 'transparent' },

  corner: { position: 'absolute', width: CORNER, height: CORNER, borderColor: '#10B981' },
  cornerTL: { top: 0, left: 0, borderTopWidth: CORNER_W, borderLeftWidth: CORNER_W },
  cornerTR: { top: 0, right: 0, borderTopWidth: CORNER_W, borderRightWidth: CORNER_W },
  cornerBL: { bottom: 0, left: 0, borderBottomWidth: CORNER_W, borderLeftWidth: CORNER_W },
  cornerBR: { bottom: 0, right: 0, borderBottomWidth: CORNER_W, borderRightWidth: CORNER_W },

  instructions: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  instructTitle: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 8 },
  instructSub: { fontSize: 13, color: '#6B7280', textAlign: 'center', lineHeight: 20 },

  backLink: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 14 },
  backLinkText: { fontSize: 13, color: '#9CA3AF' },

  permContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 32 },
  permIconBox: {
    width: 90, height: 90, borderRadius: 45,
    backgroundColor: '#ECFDF5',
    justifyContent: 'center', alignItems: 'center', marginBottom: 24,
  },
  permTitle: { fontSize: 20, fontWeight: '700', color: '#111827', marginBottom: 12, textAlign: 'center' },
  permSubtitle: { fontSize: 14, color: '#6B7280', textAlign: 'center', lineHeight: 22 },
  permText: { fontSize: 15, color: '#6B7280' },
});
